### ISSUE TITLE
Impossible de changer la famille une fois qu'on a rentré une valeur.

### ISSUE THREAD

**Issue by Ulty** [stephaned68/COF2e#1]
Une fois qu'on a choisi une valeur de famille, il semble impossible de la changer.

**Comment by stephaned68** [comment]
Cet input utilise une datalist. Vu qu'on n'est pas en sanitization legacy sur la fiche, j'ai utilisé toute ce qui était disponible ;-)

Mais c'est un peu batard, parce qu'une datalist ce n'est pas vraiment un select, c'est plutôt l'équivalent d'une combobox dans les GUI WinForms : tu as une liste de choix qui sont des suggestions, mais tu peux écrire n'importe quoi dans le champ

Si tu effaces la valeur, ça réaffiche la liste des familles de profils. Je vais ajouter un attribut title="..."  pour indiquer qu'il faut effacer la valeur pour revoir la liste de choix

**Comment by Ulty** [comment]
Arf, j'aurais dû y penser, j'ai eu le même soucis avec les catégories d'équipement.

Bon, pour les familles, a priori on ne peut avoir autre choses que les 4 du livre de base ? Donc un vrai select semblerait mieux, non ?
