### ISSUE TITLE
La famille n'impacte pas le DR

### ISSUE THREAD

**Issue by Ulty** [stephaned68/COF2e#2]
Il me semble que le DR est entièrement déterminé par le choix de la famille, donc ça devrait pouvoir s'automatiser ?

**Comment by stephaned68** [comment]
Oui, je vais regarder ça. 
Je crois que j'ai l'ai déjà fait à l'import d'un blob JSON. D'ailleurs je crée aussi un buff de +1 DR en cas de profil de Mystique, et un buff de +1 PC en cas de profil d'Aventurier
