### ISSUE TITLE
Alias

### ISSUE THREAD

**Issue by Ulty** [stephaned68/COF2e#4]
Serait-il possible d'avoir un champ quelque part pour noter un nom de personnage alternatif. Ça existe sur la fiche COF1, et je l'utilise pas mal pour les personnages incognito, ou dont les joueurs ne connaissent pas encore le nom. Au moment où les joueurs apprennent le nom du  personnage, il est ensuite possible d'échanger le nom et le nom alternatif. Pour COF1 je faisais ça avec le script, mais je pense que ça devrait pouvoir se faire dans la fiche, non ?

**Comment by stephaned68** [comment]
Tu peux me rappeller le fonctionnement STP ?
Alias c'est le vrai nom ou le faux ? Parce que sur les pancartes des jetons c'est le pseudo attribut @{character_name} qui est affiché. Donc on met le vrai nom dans le champ alias et on prévoit un bouton pour basculer alias > character_name ?

**Comment by stephaned68** [comment]
J'ai implémenté la chose. 
On clique sur le label Alias dans l'entête de la fiche (en fait c'est un bouton d'action plat & transparent) et ça copie dans le character_name
Mais ça ne change pas le token par défaut hélàs, ça ne peut être fait que par script MOD. Je vais essayer de voir s'il est possible d'interagir avec un script "standard" comme TokenMod depuis la fiche via Custom Roll Parsing

**Comment by Ulty** [comment]
Pour la partie avec le token, je compte bien gérer ça avec le script associé. Pas besoin de faire installer un autre script.

**Comment by stephaned68** [comment]
Quelle serait la commande de COFantasy à utiliser pour changer le nom du token ?

**Comment by Ulty** [comment]
En COF1, je faisais ça en sélectionnant un token, donc j'avais l'identifiant de la fiche associée. Si ça part de la fiche, je me demande s'il y a moyen de passer l'identifiant de la fiche à la commande. J'ai bien peur que non, et donc le script n'aurait que le nom, et rien n'empêche d'avoir 2 fiches avec le même nom. Peut-être le mieux serait que la fiche écrive une demande dans un attribut, le script écoute les changements de cet attribut, et quand il en voit un, il fait le changement de nom sur les tokens associés à la fiche (et efface l'attribut).

**Comment by stephaned68** [comment]
J'ai ajouté un nouvel attribut pour l'interaction avec le script : 
```
      const cofantasy = `alias|${charId}|${alias}`;
      setAttrs({ character_name: alias, alias: "", cofantasy });
```
Tu as donc **alias** pour identifier l'action, suivi du **character_id** et de l'alias (= "vrai" nom)
Tiens-moi au courant

**Comment by Ulty** [comment]
La commande devrait être `!cof2-reveler-nom`. Mais je pense qu'on devrait effectivement essayer de passer par le changemennt d'attribut pour les communications avec le script, il a y a des chances que ce soit pus efficace. Et quand on passe par l'attribut, pas besoin d'écrire le charId.

Une remarque en passant : pourquoi effacer l'alias ? Je me disais qu'échanger les 2 noms permettait de ne rien perdre. En même temps, je n'ai pas forcément d'expérience où j'ai eu besoin de garder le premier nom, donc je te laisse décider.

**Comment by stephaned68** [comment]
- L'ancien nom connu qui a été remplacé par l'alias est stocké dans le champ notes (onglet Equipement & Divers)
- L'attribut cofantasy reçoit comme valeur alias|<nouveau nom>|<ancien nom>
J'avais en effet oublié que quand le script MOD reçoit l'événement de changement de valeur d'attribut, il a le character_id propriétaire dans l'objet attribute et il peut donc remonter au token qui représente ce personnage

**Comment by Ulty** [comment]
Il faudra espérer que personne ne va mettre de | dans le nom ou l'alias... Ou alors, tu peux peut-être juste mettre `alias {ancien nom}`, vu que le nouveau nom je peux le retrouver dans l'attribut `character_name` ?

**Comment by stephaned68** [comment]
L'attribut `cofantasy` sera maintenant chargé avec du JSON sérialisé, avec une structure standard : 
- une propriété `action` contenant le type d'événement
- une propriété `param` contenant les données associées à l'évenement

Pour la révélation du vrai nom, ce sera donc : 
```
{
  action: "alias",
  param: "... ancien nom ..."
}
```

**Comment by Ulty** [comment]
Excellente idée. On pourra garder la même interface pour d'autres interractions entre la fiche et le script.

**Comment by Ulty** [comment]
Je viens de remarquer un truc mineur : le champ de l'alias n'est pas aligné avec le mot `Alias`.

**Comment by stephaned68** [comment]
Ca doit être mes yeux (JC Dusse inside), je ne vois pas de différences avec les autres champs de la section identité
Le label "Niveau" est décalé vers le haut, mais il y a des bizarreries CSS que j'ai renoncé à comprendre et lutter. Tant pis si ce n'est pas nickel, je tiens à mes derniers cheveux... ;-)

**Comment by stephaned68** [comment]
Moi je vois ça sur Chrome : 
![image](https://github.com/user-attachments/assets/6d9f1b8a-b09b-4f71-95f2-62a7627dfb0d)

Mais c'est comme toi sur Firefox. C'est beau les technos standard des interouèbes
Je vois si je peux faire qqch...

**Comment by Ulty** [comment]
Très étrange. J'ai utilisé Chrome, pourtant, là.

**Comment by Ulty** [comment]
Ah, en fait ça va mieux quand j'agrandis la fiche pour que tout tienne sur une ligne. C'est juste ma fenêtre qui était trop petite. C'est vraiment anecdotique, du coup.

**Comment by stephaned68** [comment]
:'(

Si je remplace la ligne 294 du CSS par : 
`grid-template-columns: 1fr 1fr 3fr 1fr 3fr;`

Ca corrige mon affichage déconnant sous Firefox. Et chez toi ?

**Comment by Ulty** [comment]
Oui, ça corrige le truc, en effet.

**Comment by Ulty** [comment]
Au niveau du script, je ne vois pas l'ajout de l'attribut `cofantasy`, et il n'apparaît pas non plus dans la liste des attributs du personnage. Possible qu'il faille ajouter l'attribut en hidden dans le html ?

**Comment by Ulty** [comment]
Je retire ce que j'ai dit. On ne voit pas l'attribut, mais le script peut quand même le gérer.

**Comment by stephaned68** [comment]
Il y a bien ça dans le html
`
  <input type="hidden" name="attr_cofantasy" value="">`

Donc ça devrait fonctionner 
Sur l'onglet attributes & abilities de Roll20, parfois l'affichage est en vrac...

**Comment by Ulty** [comment]
Depuis la dernière version, quand je clique sur Alias, la fiche génère un attribut cofantasy vide. Il faut que je regarde si par hasard le script ne recevrait pas l'event avant que l'attribut soit écrit, mais ça marchait hier :(

**Comment by stephaned68** [comment]
Curieux, je n'ai pas touché ce bout de code dans le dernier commit
