### ISSUE TITLE
Numérotation des champs répétables

### ISSUE THREAD

**Issue by Ulty** [stephaned68/COF2e#6]
À ma connaissance, il n'est pas possible de faire référence à un champ donné parmi des champs répétables depuis une commande. La seule façon pratique que j'avais trouvée pour COF1, c'est de faire numéroter les champs par la fiche, et je n'avais plus qu'à faire référence au numéro.

Serait-il possible d'ajouter ça pour le attaques, dans un premier temps ?

**Comment by stephaned68** [comment]
Les attributs des champs dans les sections répétables ont pour nom repeating_(nom-de-section)_(id)_(nom-du-champ)
Il faut avoir la liste des ids pour une section donnée. 
J'avais codé une fonction qui fait ça dans le script companion que j'ai fait pour COC et COG.
Cf https://github.com/stephaned68/COCGSheetHelper/blob/main/cosh.js 
La fonction s'appelle repeatRowIds()
Mais je ne comprends puet-être pas l'utilisation exacte que tu veux en faire...

**Comment by Ulty** [comment]
Oui, je sais trouver comme ça, et c'est ce que j'utilise en interne, mais c'est vraiment pas facile d'utilisation au niveau des lignes de commande. Si j'ai un numéro d'attaque, l'utilisateur va bien plus facilement pouvoir écrire `!cof2-attack n`. Je ne saurais même pas comment un joueur peut trouver l'id en question.

**Comment by stephaned68** [comment]
Ce qui serait encore plus simple pour un joueur, c'est d'indiquer le nom de l'attaque (et adjoindre un no séquentiel si plusieurs attaques ont le même nom), bref, utiliser un langage naturel
Je vais pomper ce qui existe sur COF1 pour numéroter les attaques ;-)

**Comment by Ulty** [comment]
Je ne voulais pas m'en remettre à l'utilisateur pour avoir un nom unique. Ça me permet aussi de faire des attaques qui font soit référence à une ligne de la fiche, soit dont les paramètres sont tous donnés en argument, soit encore en utilisant l'information de l'arme en main. Mais je dois pouvoir utiliser une autre syntaxe pour tous ces cas, c'est peut-être plus simple, en effet.

**Comment by stephaned68** [comment]
Dans le dernier commit, j'ai implémenté la numérotation des attaques
Moins compliqué que je ne pensais, à moins que quelque chose m'échappe.
Un gestionnaire d'événement sur `change:repeating_armes:arme-nom` (ajout d'une attaque), `change:_reporder:armes` (réorganisation des lignes) et `remove:repeating_armes` (suppression d'une ligne). On récupère la liste ordonnées des ids via la fonction indiquée dans le wiki Roll20, on numérote à la volée et on assigne l'attribut `arme-label`. Pas besoin d'un attribut `max_label`...

**Comment by Ulty** [comment]
Ça signifie que tu renumérote quand on change l'ordre des attaques ?

**Comment by stephaned68** [comment]
Oui. Faut pas ?

**Comment by Ulty** [comment]
Vaut mieux pas: si des macros sont déjà écrites qui font référence à une attaque, c'est mieux que ça ne casse pas quand on change l'ordre ou qu'on supprime une attaque. Sinon, il faut aller vérifier toutes les macros au moindre changement.

**Comment by stephaned68** [comment]
C'est peanuts à retirer. 
Je viens de refaire un commit (en me gourant de ref d'Issue, évidemment)

**Comment by stephaned68** [comment]
Je pense qu'il faut quand même que je revois le code. Si tu supprimes une ligne au milieu de 3 existantes et que tu en rajoutes une nouvelle, le no de celle précédemment supprimée n'est pas réutilisé ? Il faut bien un max et toujours faire +1 à chaque ajout, et ne pas toucher à un no déjà attribué.

**Comment by Ulty** [comment]
Si tu sais réutiliser le numéro de celle supprimée, je dirais tant mieux. Le max m'avait paru plus simple, mais je n'avais peut-être pas assez réfléchi.

**Comment by stephaned68** [comment]
Le dernier commit reproduit en principe la fiche COF1
- Quand on ajoute une attaque à laquelle on donne un nom, on parcourt les attaques et on attribue le max_label +1 à la dernière
- On ne fait rien quand une attaque est supprimée ou que l'ordre des lignes est changé
Peut-être un jour prévoir un bouton dans l'onglet configuration qui ferait une renumérotation ?

**Comment by stephaned68** [comment]
Ajout d'un bouton dans l'onglet Script pour faire une renumérotation des attaques
