### ISSUE TITLE
Gestion des compagnons

### ISSUE THREAD

**Issue by stephaned68** [stephaned68/COF2e#9]
**Automatiser le calcul des attributs d'un PNJ en fonction des attributs d'un PJ dont il est le compagnon**

Dans la configuration d'une fiche de PNJ, ajouter 
- le nom du PJ dont le PNJ est le compagnon
- l'expression de calcul de la Défense, des PV max, de l'initiative et du score d'attaque en indiquant l'attribut du PJ utilisé dans le calcul entre [...]

![image](https://github.com/user-attachments/assets/5df5376e-ed0e-4280-a618-2fd9f8089193)

Le calcul est effectué à chaque ouverture de la fiche de PNJ ainsi qu'au changement d'une expression

**Comment by Ulty** [comment]
Excellent ! Je croyais qu'il n'était pas possible de lire les attributs des autres fiches depuis le sheetworker.
